services:
  # Backend API
  backend:
    build: ./BACKEND
    container_name: guruconnect-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://apicreator04_db_user:n7P1CTUTFUI3EPrY@cluster0.1vaky5o.mongodb.net/guruconnect?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretkey
      - FRONTEND_URL=https://mentorconnect-hazel.vercel.app
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
